#!/usr/bin/env bash
# claude-review.sh — PR review agent
# Analyzes a PR diff and produces a structured review comment
# Usage: bash claude-review.sh --pr https://github.com/owner/repo/pull/123

set -euo pipefail

show_help() {
  cat <<'HELP'
Usage: bash claude-review.sh [OPTIONS]

Options:
  --pr URL         Full GitHub PR URL (e.g. https://github.com/owner/repo/pull/123)
  --diff FILE      Local diff file to review
  --output FILE    Write output to file (default: stdout)
  --help           Show this message
HELP
  exit 0
}

PR_URL=""
DIFF_FILE=""
OUTPUT_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pr)       PR_URL="$2"; shift 2 ;;
    --diff)     DIFF_FILE="$2"; shift 2 ;;
    --output|-o) OUTPUT_FILE="$2"; shift 2 ;;
    --help|-h)  show_help ;;
    *)          echo "Unknown: $1"; exit 1 ;;
  esac
done

# Get the diff content
if [[ -n "$PR_URL" ]]; then
  if [[ "$PR_URL" =~ github\.com/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
    OWNER="${BASH_REMATCH[1]}"
    REPO="${BASH_REMATCH[2]}"
    PR_NUM="${BASH_REMATCH[3]}"
  else
    echo "Invalid PR URL format. Expected: https://github.com/owner/repo/pull/123"
    exit 1
  fi

  echo "Fetching PR #$PR_NUM from $OWNER/$REPO..." >&2
  DIFF=$(curl -sL -H "Accept: application/vnd.github.v3.diff" \
    "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM" 2>/dev/null || echo "")

  if [[ -z "$DIFF" ]]; then
    DIFF=$(curl -sL "https://github.com/$OWNER/$REPO/pull/$PR_NUM.diff" 2>/dev/null || echo "")
  fi

  if [[ -z "$DIFF" ]]; then
    echo "Failed to fetch PR diff"
    exit 1
  fi

  PR_DATA=$(curl -sL -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM" 2>/dev/null || echo "{}")
  PR_TITLE=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('title','N/A'))" 2>/dev/null || echo "N/A")
  PR_BODY=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('body','')[:500])" 2>/dev/null || echo "")
  PR_AUTHOR=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['user']['login'])" 2>/dev/null || echo "N/A")
elif [[ -n "$DIFF_FILE" ]]; then
  DIFF=$(cat "$DIFF_FILE")
  PR_TITLE="N/A (local diff)"
  PR_BODY=""
  PR_AUTHOR="N/A"
  OWNER=""; REPO=""; PR_NUM=""
else
  echo "Either --pr or --diff is required"
  exit 1
fi

echo "Diff fetched ($(echo "$DIFF" | wc -l) lines)" >&2

# Statistics
CHANGED_FILES=$(echo "$DIFF" | grep '^diff --git' | sed 's|diff --git a/||;s| b/.*||' | sort -u || echo "unknown")
ADDITIONS=$(echo "$DIFF" | grep '^+' | grep -v '^+++' | wc -l)
DELETIONS=$(echo "$DIFF" | grep '^-' | grep -v '^---' | wc -l)
TOTAL=$((ADDITIONS + DELETIONS))
EXTS=$(echo "$CHANGED_FILES" | sed 's/.*\.//' | sort -u | tr '\n' ', ' | sed 's/,$//')

# Risk detection
RISKS=()
echo "$DIFF" | grep -qiE '(password|secret|api.?key|token.*=.*["'"'"'])' 2>/dev/null && RISKS+=("Possible secret/key leak detected")
echo "$DIFF" | grep -qiE '(TODO|FIXME|HACK|XXX|TEMP|WIP)' 2>/dev/null && RISKS+=("Contains TODO/FIXME/HACK markers")
echo "$DIFF" | grep -qiE '(console\.log|println|echo.*debug|var_dump|dd\()' 2>/dev/null && RISKS+=("Debug code left in changes")
echo "$DIFF" | grep -qiE '(eval\(|exec\(|shell_exec|system\(|passthru|popen)' 2>/dev/null && RISKS+=("Dangerous function usage (eval/exec/system)")
echo "$DIFF" | grep -qiE '(DROP TABLE|DELETE FROM|TRUNCATE)' 2>/dev/null && RISKS+=("Destructive database operations")
[[ $TOTAL -gt 500 ]] && RISKS+=("Large PR (${TOTAL} lines) — consider splitting")
[[ ${#RISKS[@]} -eq 0 ]] && RISKS+=("No obvious security or quality risks detected")

# Confidence
if [[ $TOTAL -eq 0 ]]; then CONFIDENCE="Low"
elif [[ $TOTAL -lt 50 ]]; then CONFIDENCE="High"
elif [[ $TOTAL -lt 200 ]]; then CONFIDENCE="Medium"
else CONFIDENCE="Low"
fi

# Output
REVIEW="## PR Review: ${PR_TITLE}

### Summary
**$(echo "$CHANGED_FILES" | wc -l) files** | **+${ADDITIONS}/-${DELETIONS}** lines
Languages: ${EXTS:-unknown}
Author: ${PR_AUTHOR}

### Changes
| Metric | Value |
|--------|-------|
| Files Changed | $(echo "$CHANGED_FILES" | wc -l) |
| Additions | +${ADDITIONS} |
| Deletions | -${DELETIONS} |
| Total Changes | ${TOTAL} |

### Risks
$(for r in "${RISKS[@]}"; do echo "- $r"; done)

### Suggestions
1. Ensure each change is intentional and tested
2. Consider edge cases (null inputs, error handling)
3. Add/update tests if not already included
4. Update docs if API behavior changes

### Confidence: **${CONFIDENCE}**

---
*Auto-generated by claude-review.sh*"

if [[ -n "$OUTPUT_FILE" ]]; then
  echo "$REVIEW" > "$OUTPUT_FILE"
  echo "Review written to $OUTPUT_FILE" >&2
else
  echo "$REVIEW"
fi
